# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import invoices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(default=invoices.models.get_unique_number, editable=False, max_length=20, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Due'), (3, 'Overdue'), (4, 'Paid')])),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Last modification')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
